services:
  - type: web_service
    name: quantiva-backend
    env: node
    region: oregon
    branch: main
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start
    autoDeploy: true

  - type: static_site
    name: quantiva-frontend
    region: oregon
    branch: main
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/dist
    autoDeploy: true
